package org.eventb.codegen.template.extensions;

import java.util.ArrayList;
import java.util.List;

import org.eventb.codegen.templates.IGenerator;
import org.eventb.codegen.templates.IGeneratorData;

public class StateMachineProgramCounterIniGenerator implements IGenerator {

	public List<String> generate(IGeneratorData data) {
		List<String> outCode = new ArrayList<String>();
		outCode.add("// Generated By StateMachineProgramCounterIniGenerator ");
		return outCode;
	}
}
